apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nationalparks-dev3-route # ArgoCDのアプリケーション名 + “-route”
  namespace: scsk-cicd-dev3 # OpenShiftのプロジェクト名
spec:
  to:
    kind: Service
    name: nationalparks-dev3-service # ArgoCDのアプリケーション名 + “-service”
  port:
    targetPort: 8080
