apiVersion: v1
kind: Service
metadata:
  name: nationalparks-service # ArgoCDのアプリケーション名 + “-service”
  namespace: scsk-cicd-dev # OpenShiftのプロジェクト名
spec:
  type: ClusterIP
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: metrics
      port: 8778
      targetPort: 8778
      protocol: TCP
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: nationalparks # ArgoCDのアプリケーション名
